name: PR to Dev

on:
  pull_request:
    branches:
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  ci:
    name: React Native CI
    uses: ./.github/workflows/ci-react-native.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
